[project]
name = "statspy"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Lucas Siqueira", email = "siqueiraq@gmail.com" }]
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.5",
    "pytest>=9.0.2",
    "scikit-learn>=1.8.0",
    "scipy>=1.16.3",
    "seaborn>=0.13.2",
    "statsmodels>=0.14.5",
]

[dependency-groups]
dev = [
    "jupyterlab>=4.4.3",
    "pytest>=9.0.2",
    "ruff>=0.11.13",
    "ty>=0.0.8",
]

[build-system]
requires = ["uv_build>=0.10.2,<0.11.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = ["."]

[tool.uv.sources]
statspy = { workspace = true }

[tool.ruff]
line-length = 120
exclude = [
    ".eggs",
    ".git",
    ".ipynb_checkpoints",
    ".ruff_cache",
    ".venv",
    ".vscode",
]

[tool.ruff.lint]
select = ["I", "F", "E", "W", "N", "PL", "ANN", "Q", "ARG", "RUF", "PERF"]
preview = true
ignore = []

[tool.ruff.format]
preview = true
quote-style = "double"
indent-style = "space"
line-ending = "auto"
exclude = []

[tool.ty.rules]
all = "error"

[tool.pytest]
minversion = "9.0"
addopts = ["-ra", "-q"]
testpaths = ["tests"]
